### ISSUE TITLE
We should probably update to ghc-8.0.1 sometime

### ISSUE THREAD

**Issue by alanz** [gregwebs/ghc-docker-dev#8]
But perhaps after the current --no-pie issue is properly resolved

**Comment by gregwebs** [comment]
Thanks for keeping things up to date. I haven't done GHC hacking in quite some time. I can definitely keep uploading images or hand that off to you (if you want to upload them elsewhere).

**Comment by alanz** [comment]
Current head now works with 8.0.1, via the ubuntu 16.10 versions from hvr's PPA
